### ISSUE TITLE
Using a single CG-NAT IPv4 Address space by default.

### ISSUE THREAD

**Issue by chirino** [nexodus-io/nexodus#1011]
### Describe the Problem Statement

Currently, each org gets a new IPAM address space for IP address allocation.  This means the same IP address could be allocated to devices in different organizations.  This would prevent a device in from being shared with other organizations.

### Describe the Enhancement

Orgs should default to using the shared CG-NAT address space which is 100.64.0.0/10, i.e. IP addresses from 100.64.0.0 to 100.127.255.255. This is about 4 Million addresses.

### Alternate Solutions

Don't support easy device sharing across organizations.

**Comment by russellb** [comment]
https://github.com/nexodus-io/nexodus/pull/998

**Comment by russellb** [comment]
implemented by #1007
