### ISSUE TITLE
nexctl: Check security-group feature flag using the API

### ISSUE THREAD

**Issue by nerdalert** [nexodus-io/nexodus#1114]
There is a fflags API endpoint where you can discover what the feature flags are set to for a given deployment. That would let you give a friendlier message about security group support being off for this service. There is a feature flag, the create/update/delete calls will fail with a "Method Not Allowed" error.

**Comment by russellb** [comment]
The context for this suggestion was the security group commands in nexctl

**Comment by russellb** [comment]
Development for this one could be done against https://qa.nexodus.io, since that should be new enough to have security-group support, but it will be off via the feature flag.

**Comment by russellb** [comment]
for the qa service, if you're using a google account, you'll need to set a password to use with nexctl by going here: https://auth.qa.nexodus.io/realms/nexodus/account/#/security/signingin

**Comment by russellb** [comment]
no longer needed, the flag is on by default and will just be removed soon
