### ISSUE TITLE
Use a db transaction when creating a user and its organization

### ISSUE THREAD

**Issue by russellb** [nexodus-io/nexodus#1117]
While reviewing #973, I noticed that a db transaction isn't used when creating a user and its corresponding organization. This can cause some parallel attempts to create resources. You can even see a spot in the code where it's trying to do its own error handling for a concurrent operation.

```
	// maybe another concurrent request created it...
	org = models.Organization{}
	if api.db.Where("owner_id = ?", userId).First(&org).Error == nil {
		return org.ID, nil
	}
```

If we create the user and its organization atomically, we won't have to handle this condition.

**Comment by Jahmilli** [comment]
Hey @russellb i'm happy to check this out :)

**Comment by russellb** [comment]
> Hey @russellb i'm happy to check this out :)

Sounds good!
