### ISSUE TITLE
Revisit DB transaction handling in CreateOrganization

### ISSUE THREAD

**Issue by russellb** [nexodus-io/nexodus#1131]
While reviewing #973, I noted that creating the default security group for the organization was done outside of the main DB transaction inside of the CreateOrganization() method. Instead of trying to handle manual rollbacks when errors occur, it makes sense to see if this could all be done in a single transaction.

As the code stands now, the result of creating an organization is not guaranteed to be consistent. For example:

- If creating the default security group fails, it will return an error, though the organization will remain in the DB, just without its default security group.
- If updating the organization with the ID of the new security group fails, the API will return an error, but the organization is still created, but without its default security group
- There is a race condition where it's technically possible for the organization to get created and then changed out from under the remaining code that is trying to update it with a default security group.

**Comment by Jahmilli** [comment]
Can pick this up
