### ISSUE TITLE
Failed peer configuration does not result in a retry to configure that peer

### ISSUE THREAD

**Issue by russellb** [nexodus-io/nexodus#1143]
I encountered a situation where a new peer (a linux host) in my nexodus organization was unable to ping another peer (a mac). Further debugging showed that the route for the new peer was not present. Some of the possible errors in creating this route are debug messages and nexd was not running in debug at this time.

`nexd` currently does not propagate any errors that occur when adding routes or adding wireguard configuration for a new or updated peer. If it fails, these configuration items will not be attempted again until the peer's configuration changes for some reason.

See this snippet from `DeployWireguardConfig()`

```
		ax.handlePeerRoute(peer)
		ax.handlePeerTunnel(peer)
```

**Comment by Jahmilli** [comment]
Im happy to look into this if possible! Would be good to get more across `nexd`
