### ISSUE TITLE
CLI flags are inconsistent some use `--organization-id` and others use `--org-id`

### ISSUE THREAD

**Issue by chirino** [nexodus-io/nexodus#1179]
### Describe the bug

CLI flags are inconsistent some use `--organization-id` and others use `--org-id`

### How to Reproduce

See nexd and nexctl usage.

### Expected Behavior

commands should use the same flag name for organizatinos.

**Comment by akoserwal** [comment]
@russellb we can close this issue

**Comment by russellb** [comment]
> @russellb we can close this issue

Thanks!  If you put `Closes #1179` in your PR description, it should automatically close the issue for you. Just FYI for the future!
