### ISSUE TITLE
IPAM resource leak when deleting organizations

### ISSUE THREAD

**Issue by russellb** [nexodus-io/nexodus#1185]
This is something I noticed while reviewing #1007.

It looks like we only release the IPv4 prefix when deleting an organization. The IPv6 prefix and the IPAM namespace appear to not be cleaned up. I have not done any validation on this yet. This is just an observation from reading the code.

In the CreateOrganization() handler, we have:

```go
		// Create the organization in IPAM
		if err := api.ipam.CreateNamespace(ctx, org.ID); err != nil {
			return err
		}

		if err := api.ipam.AssignPrefix(ctx, org.ID, request.IpCidr); err != nil {
			return err
		}

		if err := api.ipam.AssignPrefix(ctx, org.ID, request.IpCidrV6); err != nil {
			return err
		}
```

and later in the DeleteOrganization() handler:

```go
	orgCIDR := org.IpCidr

	if orgCIDR != "" {
		if err := api.ipam.ReleasePrefix(c.Request.Context(), org.ID, orgCIDR); err != nil {
			c.JSON(http.StatusInternalServerError, models.NewApiInternalError(fmt.Errorf("failed to release ipam organization prefix: %w", err)))
			return
		}
	}
```

**Comment by akoserwal** [comment]
@russellb is this still an issue, or can be closed?

**Comment by akoserwal** [comment]
@russellb I will work on it
