### ISSUE TITLE
Rename child-prefix to advertise-network

### ISSUE THREAD

**Issue by nerdalert** [nexodus-io/nexodus#1186]
Instead of nexd `--child-prefix` rename it to `--advertise-cidr` in the nexd agent CLI.

This can be broken up into multiple PRs. One for the nexd agent side and one for the api-server schema. Feel free to close this and open two separate ones if you would prefer that or are only comfortable tackling the agent side.

An example of doing a database rename migration can be found here: https://github.com/nexodus-io/nexodus/blob/main/internal/database/migration_20230314_0000/20230314-0000.go

*Note* , in that example, I unnecessarily added all of the structs. You would only need to add the struct you are renaming. Feel free to ping @nerdalert with any questions!!

**Comment by cyneptic** [comment]
Hey, i'd like to attempt this.

**Comment by nerdalert** [comment]
Awesome! Thanks @cyneptic just hit me in Discord if you run into any issues!
