### ISSUE TITLE
CLI flags inconsistent `nexctl --host` vs `nexd --service-url`

### ISSUE THREAD

**Issue by chirino** [nexodus-io/nexodus#1231]
### Describe the bug

CLI flags are inconsistent between `nexctl --host` and `nexd --service-url`.  They seem to be for the same purpose.  

### How to Reproduce

See usage info for both commands.

### Expected Behavior

Both commands should use the same flag.

**Comment by russellb** [comment]
I vote `--service-url`, though the behavior and defaults are not quite the same.

The default in `nexctl` has an `api` prefix while the default for `nexd` does not. It would be nice to make the behavior of the options the same as part of making the option names the same.

**Comment by chirino** [comment]
> I vote `--service-url`, though the behavior and defaults are not quite the same.
> 
> The default in `nexctl` has an `api` prefix while the default for `nexd` does not. It would be nice to make the behavior of the options the same as part of making the option names the same.

I agree with all the above.
