### ISSUE TITLE
Support `--insecure-skip-tls-verify` in `nexctl` commands

### ISSUE THREAD

**Issue by mkolesnik** [nexodus-io/nexodus#1238]
### Describe the Problem Statement

This flag is available in `nexd` but not in `nexctl`, please add it to enable easier testing in cases where trusting the self signing CA is not trivial (e.g. on a separate K8s environment deployed on kind).

**Comment by akoserwal** [comment]
I can see the flag is available for nexctl https://github.com/nexodus-io/nexodus/blob/main/cmd/nexctl/main.go#L68
