### ISSUE TITLE
Nexd Agent ballooned 40mb 

### ISSUE THREAD

**Issue by nerdalert** [nexodus-io/nexodus#1298]
Somewhere in the past couple of PRs ~#1294 the binary blew up from 20mb to 60mb. Looks like a bunch of k8s dependencies got introduced though I didn't see them in any recent PRs around 1294 quick glance.

You can see the k8s deps appearing with `go build -v -a` on main.

Here is a quick asset breakdown of before and after:
- before:
![binsize](https://github.com/nexodus-io/nexodus/assets/1711674/144d082f-f228-4557-92f1-468b9bc5b19f)

- after:
![binsize](https://github.com/nexodus-io/nexodus/assets/1711674/14172e1d-c092-48d6-99ef-6b3e57c3f5df)

**Comment by russellb** [comment]
@nerdalert #1278 from @chirino added the kube dependencies. We may need to rethink that one.

**Comment by chirino** [comment]
Maybe if I stick to the non-typed kube client, it would reduce the load.

**Comment by nerdalert** [comment]
Thanks all! <3
