### ISSUE TITLE
Nested containers on EC2 instances peering issue when NACL permits the WG UDP port on both sides.

### ISSUE THREAD

**Issue by nerdalert** [nexodus-io/nexodus#1322]
This is a scenario depicted in the diagram. This breaks when all UDP is permitted, you start seeing ICMP port unreachables. The nested containers on two separate VMs can peer via wireguard when the ACLs are not permitting the WG UDP ports. It breaks when the WG UDP ports are explicitly allowed.  Note: This does not occur when wg/nexd is running on the ec2 instance itself, only nested in containers and only when the Wireguard UDP port is explicitly opened in the secGroup. Its not a huge issue since you would rarely blindly open all UDP traffic. We can also do a workaround with `--listen-port` to lock the node down to a particular port or range that could be blocked in the secgroup if for some reason all UDP ephemeral ports needed to be opened.

I scratched my head on this for a few days and am getting diminishing returns at this point. The workaround is just to not explicitly open  the UDP port in the EC2 instance security group but I would like to get the root cause of this at some point. Its as much a wireguard thing as anything. This can be replicated if the hosts are in the same VPC or different VPCs. The common issue is it only happens when the WG UDP ports are explicitly open. 

You can replicate it without Nexodus to rule things out with just Podman or Docker on two different ec2 nodes. You don't need a STUN to open the ports since they will open with a 1:1 port mapping if there are no conflicts which is generally the case.

```
### Start two NEXD containers or a container with wireguard installed:
docker run -d --network bridge             --cap-add SYS_MODULE             --cap-add NET_ADMIN             --cap-add NET_RAW             --sysctl net.ipv4.ip_forward=1             --sysctl net.ipv6.conf.all.disable_ipv6=0             --sysctl net.ipv6.conf.all.forwarding=1             quay.io/nexodus/nexd sleep 100000

### host-1 ec2 instance (x.x.x.x is the ip of host-2) :

wg genkey | tee privatekey | wg pubkey > publickey
sudo ip link add wg0 type wireguard
sudo ip link set mtu 1420 up dev wg0
sudo ip -4 address add 10.200.0.1 dev wg0
sudo ip -4 route add 10.200.0.2/32 dev wg0

sudo wg set wg0 listen-port 33333 private-key /privatekey
sudo wg set wg0 peer "LO5qZmwcWty6Hsc0uMRNb4Q8fnpcqKJg1UQrsOGuuEk=" allowed-ips 10.200.0.2/32 persistent-keepalive 25  endpoint x.x.x.x:44444

### host-2 ec2 instance (y.y.y.y is the ip of host-2) :

wg genkey | tee privatekey | wg pubkey > publickey
sudo ip link add wg0 type wireguard
sudo ip link set mtu 1420 up dev wg0
sudo ip -4 address add 10.200.0.2 dev wg0
sudo ip -4 route add 10.200.0.1/32 dev wg0

sudo wg set wg0 listen-port 44444 private-key /privatekey
sudo wg set wg0 peer "6g83cD/Bpno8//rikITyg8ku2Bx/uPuXIbQaqpXJ5SQ=" allowed-ips 10.200.0.1/32 persistent-keepalive 25  endpoint y.y.y.y:33333
```

<img width="536" alt="image" src="https://github.com/nexodus-io/nexodus/assets/1711674/93663ad2-5f31-492f-92a2-7eae23bcb471">

**Comment by russellb** [comment]
#1431 should address this by doing a fallback to relay connectivity when better methods fail
