### ISSUE TITLE
Nexd relay doesn't advertise child prefixes to its peers

### ISSUE THREAD

**Issue by nerdalert** [nexodus-io/nexodus#1536]
Here is an example dump from a relay. I think adding the child-prefix to the peer will enable reachability from spoke relay-only nodes:

```
$ sudo wg show wg0 dump
eJHkc5w+wPKuWACwK3MfQ0qT/tgRg4p/lFKiJEl5zFk=	IAIMKPbWNCs9GDnH03RnmwkBdObcgpvdimY8+QOWTQM=	50336	0xca6c
4kFJVTNiDZ2opwm+JC0TfHUDV4dH0D6EM9dyVFl8EHk=	(none)	3.85.122.146:51820	100.64.0.0/10,200::/64	1697648726	2308	2476	20
```

I verified that all child-prefixes need to be added to each peers to enable forwarding through the relay. An ex:

```
wg set wg0 peer "4kFJVTNiDZ2opwm+JC0TfHUDV4dH0D6EM9dyVFl8EHk=" allowed-ips 100.64.0.0/10,200::/64,172.24.100.0/24 persistent-keepalive 25  endpoint 3.85.122.146:51820
```

**Comment by russellb** [comment]
This is trickier than it sounds because relay connectivity is done on a per-peer basis, and it's dynamic (can change over time as conditions change). I'm the most recent one in this code, so I'll take this on.

**Comment by russellb** [comment]
some notes from brainstorming this issue:

<img width="1391" alt="image" src="https://github.com/nexodus-io/nexodus/assets/309258/d0b6f597-24e4-49c2-b4a5-0968efd178cc">

I've been adding some unit tests to this code before coming back to tackle this scenario. Now that the code is easier to unit test, this will be easier to tackle.
