### ISSUE TITLE
ui: Add Create Device Form

### ISSUE THREAD

**Issue by dave-tucker** [nexodus-io/nexodus#154]
User should be able to register a device via the UI. This would take only the WG public key as input.
For fancy-pants bonus points, this would generate a pub/private key pair client-side (so pub key is never seen by the server) and tells the user to upload the public key file.

**Comment by russellb** [comment]
I consider this complete, though different than originally envisioned. You can create a device specific "Registration Token" in the UI, which allows you to specify some configuration for the device prior to it coming online.

https://qa.nexodus.io/#/reg-keys/create

cc @chirino
