### ISSUE TITLE
Rejoining device as a relay, doesn't mark it relay.

### ISSUE THREAD

**Issue by vishnoianil** [nexodus-io/nexodus#1566]
### Describe the bug

If you connect the device as a normal device, but if you reconnect the same device as a relay, it doesn't update it's relay flag.

### How to Reproduce

Connect nexd. Disconnect and reconnect it using `nexd relay` , and check the web-ui (or debug log), it won't update the relay flag.

### Expected Behavior

If the device rejoin as a Relay, it should be marked as a Relay. If we don't want to allow any device to convert to relay, we should deny onboarding of the device if it comes back as a relay.

**Comment by vishnoianil** [comment]
@chirino pushed this draft PR for review, and locally tested it but didn't work. Any pointer what am i missing here?

**Comment by russellb** [comment]
There's an open bug for adding test coverage for this: #367.

This bug had happened before: #185, and was fixed in #365

**Comment by vishnoianil** [comment]
> There's an open bug for adding test coverage for this: #367.
> 
> This bug had happened before: #185, and was fixed in #365

I think It regressed when HubRouter bits were removed. Added test coverage in https://github.com/nexodus-io/nexodus/pull/1568
