### ISSUE TITLE
Combining --stun with --exit-node produces errors on linux

### ISSUE THREAD

**Issue by butler54** [nexodus-io/nexodus#1574]
### Describe the bug

if on linux: 

`NEXD_ARGS="--service-url https://try.nexodus.io router --exit-node"`
It appears to succeed

if
`NEXD_ARGS="--stun --service-url https://try.nexodus.io router --exit-node"`

the following error line is produced
` {"level":"fatal","ts":"2023-11-02T05:12:56.321Z","caller":"nexd/main.go:202","msg":"failed to setup this device as an exit-node: failed to add nftables rule nexodus-exit-node: nft command: nft \"add rule inet nexodus-exit-node postrouting oifname  masquerade\" failed: exit status 1\n"}`

### How to Reproduce

Install nexd on centos stream 9 with dnf - note `nexd` on centos stream 9 should specify `nftables` as a dependency.

alter the `NEXD_ARGS` in `/etc/sysconfig/nexodus` and restart the service.

### Expected Behavior

EIther:
1. A logical error message.
2. Something not to 

### Deployment Environment

Machine is a centos9 streams vm on IBM Cloud with a 2 core 8GB footprint.

system is deployed with a permissive security group.

**Comment by vishnoianil** [comment]
@butler54 #1575 should fix this, but i would like @nerdalert to look at it, as it's his area of expertise.

**Comment by russellb** [comment]
> @butler54 #1575 should fix this, but i would like @nerdalert to look at it, as it's his area of expertise.

#1577 is another approach to fix this. The `--stun` option doesn't appear to do anything useful anymore.
