### ISSUE TITLE
apex: Make the client a daemon/client binary.

### ISSUE THREAD

**Issue by dave-tucker** [nexodus-io/nexodus#168]
On Linux a systemd service, on Mac a plist, on Windows a service etc...
The daemon handles:
- User authentication
- Device registration
- Peer setup
- Polling for changes

It also exposes and API which would be used to:
- Configure the daemon
- Start/Stop the VPN

Let's call it `apexd`

The advantage to running as a daemon is that all the OS-specific code lives in the daemon, allowing us to produce os-agnostic clients.

For example, we could write a very simple GUI in react-native that speaks to the daemon on a well-known port/location (i.e unix socket (or windows named-pipe)). That GUI could work on any OS.
Similarly, a CLI would operate in the same manner.

**Comment by russellb** [comment]
I'm going to close this as complete now. There's a UNIX socket control interface and `nexctl` that can talk to it. `systemd` integration is done and packaged up as an rpm. Control via `nexctl` doesn't work on mac or windows, and there's plenty of features that could be added, but I'd rather track that as individual follow-up issues.
