### ISSUE TITLE
Online Status no longer working

### ISSUE THREAD

**Issue by russellb** [nexodus-io/nexodus#1837]
On try.nexodus.io, all of my devices show up as offline, though I can verify that all of them are functional. It seems to be a regression somewhere.

<img width="368" alt="image" src="https://github.com/nexodus-io/nexodus/assets/309258/3ad21206-1560-4ec8-9d7d-d03257b2f695">

**Comment by nerdalert** [comment]
nexctl showing the same so it may be the redis interaction on the API server. Hiram currently looking at the issue as well.
https://github.com/nexodus-io/nexodus/blob/main/internal/handlers/online_tracker.go
