### ISSUE TITLE
logging: Support Log Export to Loki

### ISSUE THREAD

**Issue by dave-tucker** [nexodus-io/nexodus#211]
Support logging to loki - available in operate-first.

**Comment by vishnoianil** [comment]
@dave-tucker @russellb If we still plan to support log export to Loki, I think we should add it to the ROSA cluster requirements?

**Comment by russellb** [comment]
> @dave-tucker @russellb If we still plan to support log export to Loki, I think we should add it to the ROSA cluster requirements?

Yeah, it's listed.

This is now blocked on #413
