### ISSUE TITLE
Deconstruct relay into it's own binary and package it into a container image

### ISSUE THREAD

**Issue by dave-tucker** [nexodus-io/nexodus#347]
Currently the relay logic is tightly baked into the `apexd` binary. Splitting this out would be awesome since then it's easy to operate a relay wherever you like.

In addition, the peering flow for relays will be different... due to #215. It's likely that we'll want to bypass user authentication and device registration etc... and instead add the relays to the peer listing statically.
In order to track this, we'll probably end up storing the relay config in the database somehow - which will allow us to clean up old relays on organization delete.

**Comment by nerdalert** [comment]
Quick thought,  I think both the relay and discovery functions should be able to be run on the same node. I would be reluctant to require another public node for simple deployments.
