### ISSUE TITLE
Peer moving between asymmetric and symmetric NAT is not updated to peers

### ISSUE THREAD

**Issue by nerdalert** [nexodus-io/nexodus#423]
### Describe the bug

Peers that come in via symmetric NAT peer only to the relay. If that peer had previously been in a full mesh (asymetric cone), it would not be updated to the peers. The peers need to delete their entries for the node that can only be relayed instead of leaving a residual  direct peer on the host from when it joined symmetrically. 

Longer term, this should be a health check on a timer to STUN servers to infer whether the NAT profile has changed. Once the schema change merges we can use `models.UpdateDevice`.

### How to Reproduce

```
# Join a node behind asymetric NAT with:
sudo ./apexd https://apex.local

# Re-join the node behind a symmetric nat cone or force it with the following:
sudo ./apexd --relay-only https://apex.local
```

The hacky workaround is to delete the key (in which the agent generates a new one) on the device and rejoin or delete the device on the api-server and rejoining.

### Expected Behavior

The old peer should be deleted and updated with the new NAT profile associated to the public key of the device.

**Comment by russellb** [comment]
This was fixed along the way.
