### ISSUE TITLE
Consistent naming for apex stack components

### ISSUE THREAD

**Issue by vishnoianil** [nexodus-io/nexodus#441]
### Describe the Problem Statement

Currently we are are using multiple names for different components across our documentation and code, such as

* Apex Stack is referred as Apex Service, Apex ApiServer, Apex Controller, Apex Control Plane, Apex SaaS
* Apex Agent is referred as hub-router, relay, agent, discovery node

It would be really helpful to write a coherent documentation and code if we can zero down on the naming of these components.

**Comment by russellb** [comment]
Resolved in #440
