### ISSUE TITLE
IPAM not releasing addresses on device delete

### ISSUE THREAD

**Issue by nerdalert** [nexodus-io/nexodus#522]
### Describe the bug

IPAM not releasing addresses on device delete

### How to Reproduce

Join a node and delete it

### Expected Behavior

to delete the IPAM lease

**Comment by russellb** [comment]
Can you update the commit message with a bit more info on how this addresses the bug? I see in the bug that "IPAM not releasing addresses on device delete" but then the change just adds a new error case, so the connection from the change to the bug isn't obvious to me.

**Comment by nerdalert** [comment]
Resolved by doing a device lookup before in order to release the address.
