### ISSUE TITLE
Support Cockroach DB

### ISSUE THREAD

**Issue by chirino** [nexodus-io/nexodus#598]
### Describe the Problem Statement

Support a DB technology that can reduce DB downtime of the service and allow the DB to horizontally scale.  

### Describe the Enhancement

We should support Cockroach DB in addition to Postgres.  Cockroach shards and replicates over several work nodes allowing it to be horizontally scalable and have higher availability than traditional single node databases.  It also support doing zero downtime upgrades of the database.

Cockroach is already highly compatible with Postgres, it uses the same client drivers and supports most of the same SQL dialect.

### Alternate Solutions

* Don't support it - this would allow us to stay more nimble by only having to support one database type, but keeping the sevice up with a high level of 9's might be harder.

### Additional context

* [How to choose between PostgreSQL and CockroachDB](https://docs.rackspace.com/blog/how-to-choose-between-postgresql-and-cockroachdb/)
* [Demo of CockroachDB's in-place rolling upgrades](https://dantheengineer.com/demo-of-cockroachdbs-in-place-rolling-upgrades/)

**Comment by russellb** [comment]
Completed in #599
