### ISSUE TITLE
Breakup and remove the --hub-router argument in nexd

### ISSUE THREAD

**Issue by nerdalert** [nexodus-io/nexodus#610]
### Describe the Problem Statement

- Currently relay is overloaded. It means both discovery and relay for symmetric NAT.
- To define that, we have a flag named `--hub-router` that mashes both functions into one flag. 

### Describe the Enhancement

- This proposes to break up  `--hub-router` into two different flags.
  - `--discovery-node` or `--discovery`  which will reconcile state and handle UDP hole-punching functionality of `--hub-router`
  - `--relay-node` or `--relay` which will handle the relaying of symmetric NAT (hub/spoke) functionality of `--hub-router`

This will enables discovery and relay functions to be run on separate nodes.

### Additional context

While we have plans to create a separate image for relay, this is a first step that is low-risk in doing so. Discovery and Relay are both constructs that will transcend to any driver in the future, getting these functions separated now will be easier now than in a couple of months.

**Comment by chirino** [comment]
+1
