### ISSUE TITLE
Turn on account sign up

### ISSUE THREAD

**Issue by dave-tucker** [nexodus-io/nexodus#633]
### Describe the Problem Statement

Remove the default `admin` and `kitteh` users.

Turn on user registration.

Add a user profile validator to check domains:
https://keycloak.discourse.group/t/user-registration-email-domain-whitelist/13298

Ideally we could set the email domain we allow users to sign up with an environment variable in the keycloak config.

For dev:
- nexodus.local
For QA/Prod:
- redhat.com

In our QA and Production deployments we MUST set up email address validation to prevent users from signing up with bogus email addresses - i.e I could use `ceo@redhat.com` or `admin@redhat.com` if we don't set up validation.
This may require using an SMTP service to send those validation emails...

**Comment by chirino** [comment]
Could we just oauth with google for qa/prod..  I think you HAVE to be a valid red hat person to get an email on that domain via google.

**Comment by dave-tucker** [comment]
> Could we just oauth with google for qa/prod.. I think you HAVE to be a valid red hat person to get an email on that domain via google.

Maybe. When I last tested this what happens is:
1. Go to `try.nexodus.local`
1. Click "Login With GitHub"
1. Go through the flow
1. You're logged in and you have a username (which is your GH username) and and ID that is your user-id

The problem being that you don't get a password created.
Without a password, you can't use `nexd --username foo --password bar` and you HAVE to use the device flow for everything. I think @nerdalert had some concerns about that.

This way seemed the shortest route to getting a working service.
The other way #285, would require us figuring out:
1. How to tell Keycloak that the user needs to add some additional information to their profile after the user sign up
1. If it can't be done as part of the account registration, we'd need to figure out how to "wrap" the keycloak service so we can let users update their profile from the nexodus UI.

**Comment by russellb** [comment]
This should be blocked on #646

**Comment by russellb** [comment]
This is done now via allowing login via Google. It requires the device login flow, but caching the API refresh token makes it tolerable for now.
