### ISSUE TITLE
authz: Restrict listing of organizations and devices to the current logged in user

### ISSUE THREAD

**Issue by dave-tucker** [nexodus-io/nexodus#644]
### Describe the Problem Statement

For orgs:

This can be done the hard way, with an SQL query.
Or you can keep the current behaviour then filter to the org IDs in the Rego policy - the query would need adjusting to add `data.token.user_orgs` to the output.

For devices:

This can be done the easy way, with SQL WHERE - `"user_id = ?", user_id`
Or you can follow the same pattern used to replicate device owner information into Rego's Store... and write the policy in OPA.
Then either return all devices THEN filter... or use the output of a helper like `user_devices` to make the query simpler.

**Comment by chirino** [comment]
We should filter in the SQL layer. Doing it in the OPA seems really weird architecturally.  Keeping a store of user/org mappings in memory seems like a good way to run into scaling problems in the future.  I kind of think that should not be there either.

**Comment by chirino** [comment]
For the first pass why don't we try to implement all the user/org permission stuff with manual gorm scope functions and then  figure out if we can generalize them so that they are driven by OPA output (like get the SQL / params from OPA so that way it can stay more configureable).

**Comment by russellb** [comment]
I believe this is done now
