### ISSUE TITLE
Link to the nexodus installer gives odd error

### ISSUE THREAD

**Issue by chirino** [nexodus-io/nexodus#672]
### Describe the bug

Followed the [Nexodus Installer](https://nexodus-io.s3.amazonaws.com/installer/nexodus-installer.sh) link on this page:

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/103255/228084396-2bf906a2-df23-4d1c-9b2a-b3b6927b7191.png">

and got this result:

<img width="819" alt="Screenshot 2023-03-27 at 6 49 56 PM" src="https://user-images.githubusercontent.com/103255/228084311-6f4813a1-b6d5-4b82-94b6-3798344144ed.png">

### How to Reproduce

click the link.

### Expected Behavior

something else.

**Comment by russellb** [comment]
looks like this got fixed in #714 (maybe included by accident, but I see the changes in there!)

**Comment by nerdalert** [comment]
FYI: added the installer to the nex S3 bucket last night. DIdn't see the issue. Probably wouldn't hurt to add it to deploy as well to automate the upload to S3.
