### ISSUE TITLE
nexd proxy: Add nexctl support

### ISSUE THREAD

**Issue by russellb** [nexodus-io/nexodus#704]
Currently, when `nexd` is running as a `proxy`, you can not use `nexctl nexd` to interact with it. There are a few reasons it is currently disabled that need to be dealt with:

- `nexd proxy` usually will not be running with elevated privileges, so its unix socket location needs to be adjusted accordingly.
- Because of how `nexd proxy` operates, there's no reason why more than one copy can't run at the same time on the same host. If we allow this, `nexctl` needs to understand this. It's probably easier to ensure only one copy is running at at time, though.

Related to #692 and #700

**Comment by chirino** [comment]
well.. maybe we should allow running multiple nexd's too.  Imagine if you want to support multiple tenants on one node.

**Comment by russellb** [comment]
Fixed in https://github.com/nexodus-io/nexodus/pull/826
