### ISSUE TITLE
e2e tests are broken on mac with docker

### ISSUE THREAD

**Issue by russellb** [nexodus-io/nexodus#741]
I just tried e2e on mac for first time and discovered that testcontainers are broken.

@chirino says that e2e on mac used to work, but broke within the last week.

**Comment by chirino** [comment]
Seems my upgrade to OS X13.3 (22E252) changed something with my Docker Desktop 4.17.0 (99724) settings.  Was getting errors like: `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?: failed to create container`.   Running the following fixed it for me:

    sudo ln -s /Users/chirino/.docker/run/docker.sock /var/run/docker.sock

**Comment by russellb** [comment]
We both figured out what was wrong on our systems. all is good it seems
