### ISSUE TITLE
Consider setting up chat for the project

### ISSUE THREAD

**Issue by russellb** [nexodus-io/nexodus#847]
We have github, but no good place for live chat discussion. We should pick one and set it up so interested parties have an easy place to jump in and discuss things.

Some options

* Slack - but the message limit on free plans is not great. We don't want to throw away important discussion history.

* Discord - doesn't have limited history like slack. not open source, but it's popular and familiar.

* Rocket.chat - or some other open source slack-like platform. I don't want to self host anything, but this one has a free hosted option: https://www.rocket.chat/pricing -- the free hosted option does have some limits

* Forget all of this and just embrace GitHub discussions as good enough: https://github.com/nexodus-io/nexodus/discussions

**Comment by dave-tucker** [comment]
+1 for Discord as I already use this for several other Rust projects.
Slack is also fine, but I find its not great with too many workspaces on the go at the same time.

**Comment by russellb** [comment]
I asked around and got [Mattermost](https://mattermost.com/pricing/) as a suggestion, as well.

**Comment by russellb** [comment]
> I asked around and got [Mattermost](https://mattermost.com/pricing/) as a suggestion, as well.

but nevermind, it's self-hosted, and I'm not interested in putting in that much effort. I want an easy button. :)

I agree with you, @dave-tucker. Discord seems to fit requirements the best.  Free / easy button / no lost history / not adding yet another app to my life.

**Comment by russellb** [comment]
https://discord.gg/sMcPywSSrQ
