### ISSUE TITLE
--request-ip can create a conflict with an existing agent

### ISSUE THREAD

**Issue by nerdalert** [nexodus-io/nexodus#90]
If a user requests an IP that is leased we are releasing that lease and reassigning it to the new requester. This can leave a node orphaned. As IPAM evolves we could only release the address if the lease is assigned to the same public key requesting the release.

**Comment by russellb** [comment]
This is no longer an issue. I tried it and it falls back to getting an IP from the pool if the requested IP is already in use. There's nothing in the nexd logs to explain what happened, but an error shows up in the apiserver log.

```
	res, err := i.client.AcquireIP(ctx, connect.NewRequest(&apiv1.AcquireIPRequest{
		PrefixCidr: ipamPrefix,
		Ip:         &TunnelIP,
		Namespace:  &ns,
	}))
	if err != nil {
		i.logger.Errorf("failed to assign the requested address %s, assigning an address from the pool: %v\n", TunnelIP, err)
		return i.AssignFromPool(ctx, namespace, ipamPrefix)
	}

```
